package com.valorant.devopshub.service;

import java.net.InetAddress;
import java.net.UnknownHostException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.Optional;

import org.springframework.boot.info.BuildProperties;
import org.springframework.stereotype.Service;

import com.valorant.devopshub.config.AppInfoProperties;

/**
 * Gathers all the "DevOps Infrastructure" runtime facts shown on the About
 * page: application version, Java version, environment, build number, git
 * commit, hostname and whether the process is running inside a container.
 *
 * Everything here is read from configuration/environment at request time -
 * nothing is hardcoded, so the same JAR/image reports different values in
 * dev, Docker and on EC2 without any code changes.
 */
@Service
public class RuntimeInfoService {

    private final AppInfoProperties appInfoProperties;

    /** Populated by Spring Boot from META-INF/build-info.properties, generated by the
     *  spring-boot-maven-plugin build-info goal (see pom.xml). May be absent if the
     *  app was run directly from an IDE without that step, hence Optional. */
    private final Optional<BuildProperties> buildProperties;

    public RuntimeInfoService(AppInfoProperties appInfoProperties, Optional<BuildProperties> buildProperties) {
        this.appInfoProperties = appInfoProperties;
        this.buildProperties = buildProperties;
    }

    public String getVersion() {
        if (appInfoProperties.getVersion() != null && !appInfoProperties.getVersion().isBlank()) {
            return appInfoProperties.getVersion();
        }
        return buildProperties.map(BuildProperties::getVersion).orElse("1.0.0-dev");
    }

    public String getEnvironment() {
        return appInfoProperties.getEnv();
    }

    public String getBuildNumber() {
        return appInfoProperties.getBuildNumber();
    }

    public String getGitCommit() {
        return appInfoProperties.getGitCommit();
    }

    public String getBuildTime() {
        return buildProperties.map(bp -> bp.getTime().toString()).orElse("unknown");
    }

    public String getJavaVersion() {
        return System.getProperty("java.version");
    }

    public String getJavaVendor() {
        return System.getProperty("java.vendor");
    }

    public String getHostname() {
        String envHostname = System.getenv("HOSTNAME");
        if (envHostname != null && !envHostname.isBlank()) {
            return envHostname;
        }
        try {
            return InetAddress.getLocalHost().getHostName();
        } catch (UnknownHostException e) {
            return "unknown-host";
        }
    }

    /**
     * Best-effort container detection. Docker creates /.dockerenv on the container
     * filesystem, and process 1's cgroup file typically references "docker" or
     * "kubepods" when containerized. This is the same technique used by many
     * real-world health/diagnostics endpoints - it is a heuristic, not a guarantee.
     */
    public String getContainerStatus() {
        if (Files.exists(Path.of("/.dockerenv"))) {
            return "containerized (docker)";
        }
        try {
            Path cgroup = Path.of("/proc/1/cgroup");
            if (Files.exists(cgroup)) {
                String content = Files.readString(cgroup);
                if (content.contains("docker") || content.contains("kubepods")) {
                    return "containerized (docker)";
                }
            }
        } catch (Exception ignored) {
            // Not fatal - fall through to "host process". This runs on every /info
            // request, so we deliberately swallow filesystem errors here rather
            // than letting a diagnostics endpoint itself become a source of 500s.
        }
        return "host process";
    }

    public Instant getServerTime() {
        return Instant.now();
    }
}
